import { FileText, Code2, Terminal, PlayCircle } from 'lucide-react';

export default function PipelineTab() {
  return (
    <div className="tab-pane active" style={{ overflowY: 'auto' }}>
      <div className="header">
        <h1>How To Compile & Run</h1>
        <p>This is exactly what happens when you run <code>script.sh</code> or <code>build.bat</code>.</p>
      </div>
      
      <div className="pipeline-container" style={{ padding: '40px' }}>
        
        <div className="pipe-step">
          <div className="pipe-icon"><FileText size={40} /></div>
          <div className="pipe-content">
            <h3 style={{ fontFamily: 'monospace', background: 'rgba(0,0,0,0.5)', padding: '5px 10px', borderRadius: '4px', display: 'inline-block' }}>
              1. yacc -d -y parser.y
            </h3>
            <p style={{ marginTop: '10px' }}>
              <strong>What it does:</strong> Yacc (or Bison) reads your grammar rules. It generates a C file for the parser (<code>y.tab.c</code>) and a header file (<code>y.tab.h</code>).
              <br/><br/>
              <strong>Why the -d flag?</strong> It tells Yacc to create the <code>y.tab.h</code> file. This file contains the numeric definitions for your tokens (like <code>#define IF 258</code>). The Lexer NEEDS this file, which is why Yacc must run first!
            </p>
          </div>
        </div>

        <div className="pipe-arrow">↓</div>

        <div className="pipe-step">
          <div className="pipe-icon"><Code2 size={40} /></div>
          <div className="pipe-content">
            <h3 style={{ fontFamily: 'monospace', background: 'rgba(0,0,0,0.5)', padding: '5px 10px', borderRadius: '4px', display: 'inline-block' }}>
              2. flex lexer.l
            </h3>
            <p style={{ marginTop: '10px' }}>
              <strong>What it does:</strong> Flex reads your regular expressions (regex). It generates a C file (<code>lex.yy.c</code>) which contains a giant <code>yylex()</code> function. This function reads text and returns the token numbers it finds from <code>y.tab.h</code>.
            </p>
          </div>
        </div>

        <div className="pipe-arrow">↓</div>

        <div className="pipe-step">
          <div className="pipe-icon"><Terminal size={40} /></div>
          <div className="pipe-content">
            <h3 style={{ fontFamily: 'monospace', background: 'rgba(0,0,0,0.5)', padding: '5px 10px', borderRadius: '4px', display: 'inline-block' }}>
              3. g++ lex.yy.c y.tab.c -o a.out
            </h3>
            <p style={{ marginTop: '10px' }}>
              <strong>What it does:</strong> Now you have two C/C++ files generated by Flex and Yacc. You use the standard GNU C++ Compiler (<code>g++</code>) to compile them together into a single executable program named <code>a.out</code> (or <code>a.exe</code> on Windows).
            </p>
          </div>
        </div>

        <div className="pipe-arrow">↓</div>

        <div className="pipe-step">
          <div className="pipe-icon"><PlayCircle size={40} /></div>
          <div className="pipe-content">
            <h3 style={{ fontFamily: 'monospace', background: 'rgba(0,0,0,0.5)', padding: '5px 10px', borderRadius: '4px', display: 'inline-block' }}>
              4. ./a.out input.txt
            </h3>
            <p style={{ marginTop: '10px' }}>
              <strong>What it does:</strong> You run your new compiler! You pass it your test C code (<code>input.txt</code>). The <code>main()</code> function inside <code>y.tab.c</code> opens the file and calls <code>yyparse()</code>, starting the whole process!
            </p>
          </div>
        </div>

      </div>
    </div>
  );
}
